-- Supabase / Postgres Schema for Africo Cash

-- 1. config table
CREATE TABLE IF NOT EXISTS public.config (
  key TEXT PRIMARY KEY,
  value NUMERIC NOT NULL
);

-- 2. banks table
CREATE TABLE IF NOT EXISTS public.banks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  short_name TEXT
);

-- 3. clients table
CREATE TABLE IF NOT EXISTS public.clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_number TEXT UNIQUE NOT NULL,
  nom TEXT NOT NULL,
  postnom TEXT,
  prenom TEXT NOT NULL,
  province TEXT NOT NULL,
  ville TEXT NOT NULL,
  commune TEXT,
  quartier TEXT,
  avenue TEXT,
  numero_residence TEXT,
  profession TEXT,
  telephone TEXT NOT NULL,
  piece_type TEXT NOT NULL,
  piece_numero TEXT NOT NULL,
  pin_hash TEXT NOT NULL,
  balance_usd NUMERIC NOT NULL DEFAULT 0,
  balance_cdf NUMERIC NOT NULL DEFAULT 0,
  agent_inscripteur TEXT,
  status TEXT NOT NULL DEFAULT 'Actif',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. agents table
CREATE TABLE IF NOT EXISTS public.agents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_code TEXT UNIQUE NOT NULL,
  nom TEXT NOT NULL,
  postnom TEXT,
  prenom TEXT NOT NULL,
  boutique_nom TEXT NOT NULL,
  province TEXT NOT NULL,
  ville TEXT NOT NULL,
  commune TEXT,
  quartier TEXT,
  avenue TEXT,
  numero_boutique TEXT,
  gps_lat NUMERIC,
  gps_lng NUMERIC,
  telephone TEXT NOT NULL,
  piece_type TEXT NOT NULL,
  piece_numero TEXT NOT NULL,
  pin_hash TEXT NOT NULL,
  banque_partenaire TEXT,
  index_cantonnement_usd NUMERIC NOT NULL DEFAULT 0,
  index_cantonnement_cdf NUMERIC NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'Actif',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. guichets table
CREATE TABLE IF NOT EXISTS public.guichets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  bank_name TEXT NOT NULL,
  agence TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  cantonnement_usd NUMERIC NOT NULL DEFAULT 250000,
  cantonnement_cdf NUMERIC NOT NULL DEFAULT 500000000,
  status TEXT NOT NULL DEFAULT 'Operationnel',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. transactions table
CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  client_account TEXT,
  counterparty TEXT,
  currency TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  fee NUMERIC NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'Reussi',
  details TEXT,
  code_retrait TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- SEED DATA

INSERT INTO public.config (key, value) VALUES 
  ('withdrawal_rate', 0.015),
  ('transfer_fee_rate', 0.02),
  ('rate_usd_to_cdf', 2870),
  ('rate_cdf_to_usd', 2900),
  ('mobile_deposit_fee_rate', 0.0),
  ('mobile_withdrawal_fee_rate', 0.01),
  ('bank_atm_withdrawal_fee_rate', 0.015),
  ('bank_deposit_fee_rate', 0.01),
  ('bank_transfer_fee_rate', 0.015),
  ('regideso_fee_rate', 0.01),
  ('electricity_fee_rate', 0.01),
  ('telecom_tv_fee_rate', 0.005),
  ('merchant_fee_rate', 0.0),
  ('payment_fee_rate', 0.01)
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.banks (name, short_name) VALUES 
  ('Rawbank', 'RAW'),
  ('Equity BCDC', 'EQ'),
  ('Trust Merchant Bank', 'TMB'),
  ('Ecobank', 'ECO'),
  ('FBNBank DRC', 'FBN')
ON CONFLICT (name) DO NOTHING;
